export { CourseHeader } from './CourseHeader'
export { CourseInfoGrid } from './CourseInfoGrid'
export { CourseActions } from './CourseActions'
export { PrerequisitesSection } from './PrerequisitesSection'
export { UnlockedCoursesSection } from './UnlockedCoursesSection'
export { CourseDescription } from './CourseDescription'
export { useCourseDetails } from './useCourseDetails'
export * from './types'
export * from './CourseDetails.styles'
